update

diff --git a/bin/git-resync b/bin/git-resync
--- a/bin/git-resync
+++ b/bin/git-resync
@@ -18,7 +18,7 @@ if [[ `git status --porcelain --untracked-files=no | wc -l` != 0 ]]; then
    exit 2
 fi
 
-git fetch upstream || echo "WARNING: could not fetch upstream!"
+git fetch --all -p || echo "WARNING: could not fetch!"
 
 commit="$1"
 if [ "$commit" == "" ]; then
